### ISSUE TITLE
Disqus thread ident instead of link

### ISSUE THREAD

**Issue by MDXDave** [nystudio107/craft3-disqus#2]
Why are you using the _ident_ param instead of the link?

https://github.com/nystudio107/craft-disqus/blob/1e06726459ed50b792db232c6f288d809da85703/src/services/DisqusService.php#L88-L89

I think the link param is quite easier to use in templates, because the default link disqus creates is the current page url.
 
```php
 ."&thread:link=" 
.$disqusIdentifier; 
```

**Comment by khalwat** [comment]
I honestly can't remember the reason I ended up going with `ident` instead of `link` -- but it doesn't seem like it'd be detrimental in any way?
