### ISSUE TITLE
Load Disqus onclick

### ISSUE THREAD

**Issue by rjdusk** [nystudio107/craft3-disqus#3]
Hi,
I was wondering if there was any possibility of having Disqus load when a button is pressed vs onload with this plugin? 

Something similar to this: https://gist.github.com/robwent/e9c321b5c200370da0cadb69e40379b7

**Comment by khalwat** [comment]
You can definitely do that if you like, but you'd need to include the Disqus scripts yourself

**Comment by khalwat** [comment]
The Disqus JavaScript is now loaded only when the comments scroll into view as of 1.1.0: https://github.com/nystudio107/craft-disqus/releases/tag/1.1.0
