### ISSUE TITLE
Ajax support

### ISSUE THREAD

**Issue by terraindesign** [nystudio107/craft3-disqus#35]
Love the plugin — but unless I'm missing something, it doesn't seem to support AJAX reload (or at least not without Disqus complaining in the console log on each request). Disqus recommends using `reset`, instead of re-embedding the js on each request.

```
DISQUS.reset({
  reload: true,
  config: function () {  
    this.page.identifier = "newidentifier";  
    this.page.url = "http://example.com/#!newthread";
  }
});
```

Thanks again for all your work!

**Comment by khalwat** [comment]
Correct, it does not handle AJAX requests currently. I'm about to release an updated version for Craft 3, Craft 4, and Craft 5. If you want to make a PR to handle AJAX appropriately, or can provide a link to an article discussing how to do it, I'd be open to it.
