### ISSUE TITLE
Is this plugin still working?

### ISSUE THREAD

**Issue by lucosius** [nystudio107/craft3-disqus#37]
Hello there,

Is it only me or this plugin doesn't work for someone else?

I'm running Craft CMS Pro 4.12.3.

**Comment by khalwat** [comment]
I'm using it on a Craft 4 and a Craft 3 website successfully, so yes, it seems to still be working.

**Comment by lucosius** [comment]
Right, that's correct. Everything is working, forgot about lazy loading :D 

So since I get this one running, I have one additional question. I can see that plugin sending user photo to Disqus if SSO enabled but it seems not to work. I cannot get user photos in the comments and it shows default avatar that is set on Disqus admin.

I found this line in the DisqusService.php file:

`$data['avatar'] = $currentUser->getPhoto();`

I'm not really good in programming but maybe someone can help me out with this to get avatars shown? 😅

**Comment by khalwat** [comment]
It's getting the Avatar from the current user's profile image in Craft.

**Comment by lucosius** [comment]
> It's getting the Avatar from the current user's profile image in Craft.

For some reason it doesn't work for me. I get default no avatar from Disqus even though I have profile image in Craft. Any ideas how to fix that?

**Comment by khalwat** [comment]
As a quick fix, try changing this line of code in `DisqusService.php`:

```php
                $data['avatar'] = $currentUser->getPhoto();
```

To this:

```php
                $data['avatar'] = $currentUser->getPhoto()->getUrl();
```

**Comment by lucosius** [comment]
> As a quick fix, try changing this line of code in `DisqusService.php`:
> 
> ```
>                 $data['avatar'] = $currentUser->getPhoto();
> ```
> 
> To this:
> 
> ```
>                 $data['avatar'] = $currentUser->getPhoto()->getUrl();
> ```

Nothing changed :?

**Comment by lucosius** [comment]
Okay, I figured out what's the problem. $currentUser->getPhoto()->getUrl() gives the path to the image so it was needed to add domain of the website to get it working.

**Comment by khalwat** [comment]
Okay so then I do need to make that change to the plugin for it to work properly then, it seems.
