### ISSUE TITLE
craft.config.get() has been deprecated

### ISSUE THREAD

**Issue by RyanRoberts** [nystudio107/craft3-disqus#5]
I'm getting this deprecation warning in Craft after a clean install of the plugin.

Message:
`craft.config.get() has been deprecated. Use craft.app.config.general.setting instead.`

Origin:
`/vendor/nystudio107/craft-disqus/src/templates/settings.twig:4`

**Comment by khalwat** [comment]
Ah yes, thanks

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-disqus/commit/f541a88e98ae1e53df8f9ed782fa75bb07562ab0
