### ISSUE TITLE
Setting to disable lazy load

### ISSUE THREAD

**Issue by rowansentesy** [nystudio107/craft3-disqus#8]
Hello there,
Enjoying your plugin and using it with Craft, but unfortunately we had to disable the lazy loading of the scripts. Our pages were short and it was odd to have to trigger a scroll or resize to load the comments. 
It would be great if we could eith pass a parameter in the disqusEmbed code or set a setting in the admin/settings to disable the lazy loading. 

Maybe I missed something and this is possible, but I couldn't figure out how to do it without changing the plugin code, which we elected to not do for now. We just reverted back to the embed code from Disqus. 

Thanks!
Rowan

**Comment by terraindesign** [comment]
I am displaying comments in a modal window triggered on click event and was wondering why they did not load unless I scrolled — now I understand. Thanks Rowan for the heads up. +1 on this request.

**Comment by khalwat** [comment]
Added the feature in the above commits.
